version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps'
    ignore:
      # these deps are managed by nx
      - dependency-name: '@angular/*'
      - dependency-name: '@angular-devkit/*'
      - dependency-name: '@schematics/angular'
      - dependency-name: 'nx'
      - dependency-name: 'eslint'
      - dependency-name: '@nx/*'
