version: 2
updates:
  # Root dependencies (Nx Workspace)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps'
    # These dependencies are handled by 'nx migrate' and should be ignored by Dependabot
    ignore:
      - dependency-name: '@angular/*'
      - dependency-name: '@angular-devkit/*'
      - dependency-name: '@schematics/angular'
      - dependency-name: 'nx'
      - dependency-name: 'eslint'
      - dependency-name: '@nx/*'
      - dependency-name: '@angular-eslint/*'
      - dependency-name: 'typescript'
    groups:
      # Build & Development Tools
      build-tools:
        patterns:
          - 'vite*'
          - 'vitest*'
          - '@vitest/*'
          - '@swc/*'
          - '@swc-node/*'
          - 'rollup-plugin-*'
          - 'jiti'
          - 'jsdom'
          - 'dotenv'
          - '@rollup/rollup-linux-x64-gnu'
          - '@typescript-eslint/*'

  # Docs dependencies (Docusaurus site)
  - package-ecosystem: 'npm'
    directory: '/docs'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps'
